apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# 1. Update the Variable for Dev
patches:
- target:
    kind: Deployment
    name: html-app-deployment
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "Development"
    - op: replace
      path: /spec/replicas
      value: 4

# 2. Update the Image Tag (CI will update this automatically later)
images:
  - name: ghcr.io/my-org/my-html-app

    newTag: latest



