apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# 1. Update the Variable for Prod
patches:
- target:
    kind: Deployment
    name: html-app-deployment
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "Production"
    # Example: Increase replicas for Prod
    - op: replace
      path: /spec/replicas
      value: 2

# 2. Update the Image Tag
images:
  - name: ghcr.io/my-org/my-html-app
    newTag: v1.0.0